filebeat.inputs:
  - type: kafka
    hosts: [ "localhost:9092" ]
    topics:
      - "ph-metric-system-log"
    group_id: "kafka-consumer-filebeat"
    visibility_timeout: 300s
    credential_profile_name: default

output.logstash:
  hosts: ["localhost:5044"]

processors:
  - decode_json_fields:
      fields: ["message"]
      max_depth: 10
      overwrite_keys: false
      add_error_key: true
      target: ""
  - script:
      lang: javascript
      id: customerName_filter
      source: >
        function process(event) {
         var objectkey = event.Get("aws.s3.object.key");
         if (objectkey != null ) {
            var objectkeyArr  = objectkey.split("/");
            if (objectkeyArr!= null  && objectkeyArr.length > 3 ){
                var customerName = objectkeyArr[1].trim();
                event.Put("customerShortName",customerName);
                event.Put("customerEnvironment",objectkeyArr[2]);
            }
         }
         var message = event.Get("message");
         var stringify = JSON.stringify(message);
         event.Put("message",stringify);
        }

# output.console:
#   output.console:
#   pretty: true
# #   hosts: [ "localhost:9200" ]
# #   elasticsearch.username: "kibana_system"
# #   elasticsearch.password: "oPSgrkPPwqJ*kLD0P1FY"